# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 10:39
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pictures',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profile_photos/'), upload_to=''),
        ),
    ]
