# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('ArticleList_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Article_Num', models.CharField(max_length=20)),
                ('Series_Name', models.CharField(max_length=200)),
                ('BrandSeg_Choice', models.CharField(choices=[('Consumer', 'Consumer'), ('Commercial', 'Commercial')], default='Consumer', max_length=200)),
                ('Device_Choice', models.CharField(choices=[('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Desktops - AIO', 'Desktops All-In-Ones'), ('Accessories', 'Accessories'), ('Workstations', 'WorkStations'), ('Tablets', 'Tablets'), ('Smart Devices', 'Smart Devices'), ('Servers Storage and Networking', 'Servers, Storage and Networking')], default='Laptops', max_length=200)),
                ('TaskLink', models.TextField(blank=True)),
                ('HLink', models.TextField()),
                ('AssetLinks', models.TextField(blank=True)),
                ('Notes', models.TextField(blank=True)),
                ('Halo', models.BooleanField(default=False)),
                ('Touch', models.BooleanField(default=False)),
                ('Convertible', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('live_date', models.DateTimeField(blank=True, null=True)),
                ('launch_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Brand_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
