# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Device_Status',
            field=models.CharField(choices=[('Live', 'Live'), ('Coming Soon', 'Coming Soon'), ('End of Life', 'End of Life')], default='Live', max_length=200),
        ),
    ]
