# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('Update_Choices', models.CharField(choices=[('/static/img/update_1.jpg', 'Promotions'), ('/static/img/update_2.jpg', 'Special Projects'), ('/static/img/update_3.jpg', 'Campaigns'), ('/static/img/update_4.jpg', 'Holidays'), ('/static/img/update_5.jpg', 'Tests')], default='/static/img/update_2.jpg', max_length=200)),
                ('text', models.TextField(blank=True)),
                ('asset', models.FileField(blank=True, upload_to='post_assets/%Y/%m/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
