# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=2000)),
                ('link_choices', models.CharField(choices=[('/static/icon/icons8-Filing Cabinet-50.png', 'Internal Ops'), ('/static/icon/icons8-Support Filled-50.png', 'Tools'), ('/static/icon/icons8-Binoculars Filled-50.png', 'Info Resource'), ('/static/icon/icons8-Whois-50.png', 'Lenovo link'), ('/static/icon/icons8-Key Filled-50.png', 'Calendar')], default='/static/icon/icons8-Support Filled-50.png', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
