# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='asset',
            field=models.FileField(blank=True, upload_to='post_assets/%Y/%m/'),
        ),
    ]
