# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_auto_20170913_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='asset',
            field=models.FileField(blank=True, upload_to='post_assets/%Y/%m/'),
        ),
    ]
