# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_auto_20170913_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Update_Choices',
            field=models.CharField(choices=[('/static/img/update_1.png', 'Promotions'), ('/static/img/update_2.png', 'Special Projects'), ('/static/img/update_3.png', 'Campaigns'), ('/static/img/update_4.png', 'Holidays'), ('/static/img/update_5.png', 'Tests')], default='/static/img/update_2.png', max_length=200),
        ),
    ]
